### ISSUE TITLE
Question for MMD loss

### ISSUE THREAD

**Issue by VinnyCSY** [Necolizer/CHASE#2]
Hello, I have a question about MMD loss.
According to the flow in the paper, Minibatch Sampling from Discrepency Minimization doesn't go through backbone of GCN(CTR-GCN, ...).
However, the output from Model_GROUP is `(self.fc(x), self.fc_person(xm))`, `xm` also passes the backbone as `x` does.
That shows that MMD loss also affect the training of backbone as CE loss does.
Did I understand the code in right way?
Thank you.

**Comment by Necolizer** [comment]
Hi, hope the following clarifications might help:
- MMD loss does NOT affect the training of backbone. MMD loss only use `x1, x2` outputs from CHASE wrapper, rather than `xm` from backbones (for group activities).
- `xm` is for the auxiliary CE loss to classify individual actions, which is a common practice adopted in Group Activities Recognition task.

**Comment by VinnyCSY** [comment]
Ah, I see. Thank you for your help.
